default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: Recipe_app

test:
  <<: *default
  database: Recipe_app_test

production:
  <<: *default
  database: scalingo_production
  username: scalingo
  password: <%= ENV["SCALINGO_DATABASE_PASSWORD"] %>
